GET https://api.web3.storage/status/bafybeialefw4rclvcgfmczgwo7fzdrfzzjm6cn7eejlhubm3h2he7lx7tu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDdBMWNlRGNkZmMxOWIzMTVhMTk1NTYwY0JBM0Y2NEI4YzY2NzU0ODYiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2MzMwNjIxMzI5MzksIm5hbWUiOiJzeW5jIn0.idpWUdJ0J6bsMdQb8_OMKqgvjvvLGOMqstrVBFLh58M

#####

GET https://api.web3.storage/car/bafybeialefw4rclvcgfmczgwo7fzdrfzzjm6cn7eejlhubm3h2he7lx7tu
Authorization: Bearer WyIweDcyNDAzZDc4NmM4MmVhOGE5NTU5MWE4Mzg2Y2U1ZjgxZmI4YWE2NzcwYjU3M2NkZTZjNGJlZDJhMmM0M2NmMWYwNzRiYzU3NjRiNzYxOTBlNjU5ZDU3MDg3M2FiOWVlM2ZmY2NiYzc0NzE1YmM3ZmQ4ZGRmNDliYzFlNGY4Y2NlMWIiLCJ7XCJpYXRcIjoxNjMzNDk0OTExLFwiZXh0XCI6MTYzMzQ5NTgxMSxcImlzc1wiOlwiZGlkOmV0aHI6MHg3QTFjZURjZGZjMTliMzE1YTE5NTU2MGNCQTNGNjRCOGM2Njc1NDg2XCIsXCJzdWJcIjpcIkZTUHFOekYtOG5hdUFJWnBaT1lRWmpvOHhndWE1UE1LZG5ZdnhzNzVMTlk9XCIsXCJhdWRcIjpcIm1UUl9NQ3JTTjU3NFVsRmIzUFdyYzYyYllHNFgyczAxemZGcHRJSkkwa2M9XCIsXCJuYmZcIjoxNjMzNDk0OTExLFwidGlkXCI6XCJlODRkNzA1Yi02YjBkLTQyM2YtYjk5MC1kYmYxODYyZTJkMmNcIixcImFkZFwiOlwiMHhhMTc2NWEzODAwNmFhMmMyYmU1Yjk1Yzg3MDVmMDBiNDJlYjBkNDY3Nzc3NzMzM2I1NDJkMmIyMmU5ODkzNzY3NDg2ODEyZmFlMjQzMDVhZWMxNTRmMGQxZjUzN2I1ZWNmYzM5ZDNkMDlmMzBlZmNmY2JjOTk0MjFjNzU5ZTc2MzFiXCJ9Il0=


#####
POST https://api.web3.storage/user/uploads/bafybeigktpu32s6zxxn4patspyacuzocva3zg7lq6trsknuvgldibu6nba/rename
accept-language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7
Authorization: Bearer WyIeGU5MWQyMjgyM2RhNGRkYWZmMjdmYmEzMjVjZTAyYjU2NTQ3ZTdkNTE3ZTEyZDY3NWNhOTZlN2RjZWU2NjFmNmU0NzAwZjY5MWM5NmY1YmNjNzc3NmI3NTBhMjNhZDViMDUyOTYxZWY2YWY5MjgzNTFhY2I0OGQwY2QzNzdmZTc5MWIiLCJ7XCJpYXRcIjoxNjMzNDk5MzI1LFwiZXh0XCI6MTYzMzUwMDIyNSxcImlzc1wiOlwiZGlkOmV0aHI6MHg3QTFjZURjZGZjMTliMzE1YTE5NTU2MGNCQTNGNjRCOGM2Njc1NDg2XCIsXCJzdWJcIjpcIkZTUHFOekYtOG5hdUFJWnBaT1lRWmpvOHhndWE1UE1LZG5ZdnhzNzVMTlk9XCIsXCJhdWRcIjpcIm1UUl9NQ3JTTjU3NFVsRmIzUFdyYzYyYllHNFgyczAxemZGcHRJSkkwa2M9XCIsXCJuYmZcIjoxNjMzNDk5MzI1LFwidGlkXCI6XCJiNDlhOTg0YS04MTU4LTRlNjktYTBlOC05MTRiOWJiYWViZDlcIixcImFkZFwiOlwiMHhhMTc2NWEzODAwNmFhMmMyYmU1Yjk1Yzg3MDVmMDBiNDJlYjBkNDY3Nzc3NzMzM2I1NDJkMmIyMmU5ODkzNzY3NDg2ODEyZmFlMjQzMDVhZWMxNTRmMGQxZjUzN2I1ZWNmYzM5ZDNkMDlmMzBlZmNmY2JjOTk0MjFjNzU5ZTc2MzFiXCJ9Il0=
cache-control: no-cache
content-type: application/json


{"name":"Upload at 2021-10"}

